### ISSUE TITLE
Bug - "#shoowtooltip Multi-Shot" in macro causes Multi-Shot cast bar to freeze permanently

### ISSUE THREAD

**Issue by nerolite** [watchyoursixx/WeaponSwingTimer-SixxFix#29]
If I include `"#shoowtooltip Multi-Shot"` in a macro that includes a _nomod_ condition for Multi-Shot, then the Multi-Shot cast bar will freeze whenever this condition is false.

The only way to remove this frozen cast bar is to begin casting a Multi-Shot or Aimed Shot and then either cancelling the cast or finishing it. Only after this will the frozen cast bar be gone.

**Bug example:** Macro example where the cast bar freezes (_given that you have a target selected and use a modifier_)
```
#showtooltip Multi-Shot
/cast [nomod] Multi-Shot
/cast [mod:ctrl] Mend Pet
```

**Comparison example:** Everything working as expected.
```
#showtooltip
/cast [nomod] Multi-Shot
/cast [mod:ctrl] Mend Pet
```

**Image of the cast bar being frozen**
![example_img](https://user-images.githubusercontent.com/6739079/99975211-3f024f80-2da2-11eb-9138-2d8ae674cc2d.png)

**Comment by watchyoursixx** [comment]
should be fixed with latest update
