### ISSUE TITLE
WeaponSwingTimer_Castbar.lua:334: attempt to call field 'FeignDeath' (a nil value)

### ISSUE THREAD

**Issue by Sansaan** [watchyoursixx/WeaponSwingTimer-SixxFix#30]
Message: ...AddOns\WeaponSwingTimer\WeaponSwingTimer_Castbar.lua:334: attempt to call field 'FeignDeath' (a nil value)
Time: Sun Apr  4 11:36:01 2021
Count: 1
Stack: ...AddOns\WeaponSwingTimer\WeaponSwingTimer_Castbar.lua:334: attempt to call field 'FeignDeath' (a nil value)
[string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Castbar.lua"]:334: in function `OnUnitSpellCastSucceeded'
[string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua"]:699: in function <...ce\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua:672>

Locals: unit = "player"
spell_id = 20904
settings = <table> {
 rel_point = "CENTER"
 backplane_alpha = 0.500000
 show_border = false
 point = "CENTER"
 show_multishot_cast_bar = true
 show_text = true
 width = 300
 enabled = true
 y_offset = -260
 x_offset = 0
 show_latency_bars = false
 height = 12
 fontsize = 12
 in_combat_alpha = 1
 ooc_alpha = 0
}
(*temporary) = nil
(*temporary) = "attempt to call field 'FeignDeath' (a nil value)"
addon_data = <table> {
 core = <table> {
 }
 player = <table> {
 }
 config = <table> {
 }
 castbar = <table> {
 }
 target = <table> {
 }
 hunter = <table> {
 }
 localization_table = <table> {
 }
 utils = <table> {
 }
}

**Comment by Sansaan** [comment]
Running WeaponSwingTimer-SixxFix-TBC-Beta-v6.2.1

**Comment by Sansaan** [comment]
Error happens during every combat after an aimed shot cast. Not seeing it happen with other shots/casts.

**Comment by watchyoursixx** [comment]
line 334 changed to .hunter. instead of .castbar. just updated.. Will push update to curse later

**Comment by Sansaan** [comment]
Much better! Thank you
