### ISSUE TITLE
TBC Beta - 58 Boost Hunter LUA Error

### ISSUE THREAD

**Issue by dandavis77** [watchyoursixx/WeaponSwingTimer-SixxFix#31]
This doesn't happen on a copied level 60 character or a brand new level 1. The Count field is just rapidly incrementing until the client tells me to Disable Addons.

> Message: ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:175: attempt to index field '?' (a nil value)
> Time: Tue Apr 20 10:07:35 2021
> Count: 1522
> Stack: ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:175: attempt to index field '?' (a nil value)
> [string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua"]:175: in function `UpdateRangeCastSpeedModifier'
> [string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua"]:218: in function `UpdateAutoShotTimer'
> [string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua"]:252: in function `OnUpdate'
> [string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua"]:581: in function <...ce\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua:578>
> 
> Locals: weapon_id = nil
> (*temporary) = <table> {
>  config_frame = WeaponSwingTimerHunterConfigPanel {
>  }
>  InitializeVisuals = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:533
>  guid = 0
>  has_moved = false
>  FontSizeEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:665
>  LoadSettings = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:122
>  is_spell_shoot = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:49
>  OnStopAutorepeatSpell = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:278
>  OnCombatLogUnfiltered = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:283
>  last_failed_time = 549338.715000
>  range_speed = 3
>  RestoreDefaults = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:140
>  OnStartAutorepeatSpell = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:269
>  UpdateRangeCastSpeedModifier = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:170
>  OnFrameDragStart = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:511
>  UpdateVisualsOnSettingsChange = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:442
>  StartCastingSpell = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:104
>  OnUnitSpellCastFailedQuiet = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:373
>  UpdateVisualsOnUpdate = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:388
>  UpdateConfigPanelValues = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:575
>  auto_cast_time = 0.520000
>  OOCAlphaOnValChange = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:757
>  OnUnitSpellCastSucceeded = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:309
>  OneBarCheckBoxOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:644
>  CooldownColorPickerOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:680
>  frame = WeaponSwingTimerHunterAutoshotFrame {
>  }
>  MultiClipColorPickerOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:728
>  HeightEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:660
>  last_shot_time = 549338.715000
>  UpdateInfo = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:151
>  shot_timer = -0.012000
>  ShowTextCheckBoxOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:650
>  YOffsetEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:675
>  XOffsetEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:670
>  EnabledCheckBoxOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:619
>  OnUpdate = <function> defined @Interface\AddOns\Weapo`

**Comment by watchyoursixx** [comment]
What version?

**Comment by dandavis77** [comment]
6.3.2

**Comment by watchyoursixx** [comment]
If you turn the add-on off, then equip the bow, and reenable, does the error go away

**Comment by dandavis77** [comment]
Yes, the errors stop as soon as I equip the bow.

**Comment by watchyoursixx** [comment]
fixed as of v6.3.3
