### ISSUE TITLE
TBC WeaponSwingTimer_Hunter.lua:149: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by dandavis77** [watchyoursixx/WeaponSwingTimer-SixxFix#32]
Version 6.3.3

On a level 60 Shaman. No errors when logging in or reloading.

However, when I open my mail and save items to my bag, I get this error:

> Message: ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:149: attempt to index field '?' (a nil value)
> Time: Thu Apr 22 12:58:06 2021
> Count: 6
> Stack: ...\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:149: attempt to index field '?' (a nil value)
> [string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua"]:149: in function `OnInventoryChange'
> [string "@Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua"]:697: in function <...ce\AddOns\WeaponSwingTimer\WeaponSwingTimer_Core.lua:676>
> 
> Locals: weapon_id = 186071
> (*temporary) = <table> {
>  HeightEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:663
>  last_shot_time = 732367.029000
>  shot_spell_ids = <table> {
>  }
>  config_frame = WeaponSwingTimerHunterConfigPanel {
>  }
>  has_moved = false
>  shot_timer = 0.520000
>  LoadSettings = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:113
>  frame = WeaponSwingTimerHunterAutoshotFrame {
>  }
>  YOffsetEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:678
>  auto_shot_ready = true
>  range_cast_speed_modifer = 1
>  scan_tip = WSTScanTip {
>  }
>  CreateConfigPanel = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:770
>  OnCombatLogUnfiltered = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:287
>  OnUpdate = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:246
>  OnUnitSpellCastFailedQuiet = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:376
>  OnFrameDragStop = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:520
>  CombatAlphaOnValChange = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:755
>  OnInventoryChange = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:142
>  is_spell_aimed_shot = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:36
>  ResetShotTimer = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:190
>  AutoShotCastColorPickerOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:707
>  OnStopAutorepeatSpell = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:283
>  is_spell_auto_shot = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:45
>  default_settings = <table> {
>  }
>  XOffsetEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:673
>  is_spell_multi_shot = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:27
>  FontSizeEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:668
>  RestoreDefaults = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:131
>  OnStartAutorepeatSpell = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:275
>  WidthEditBoxOnEnter = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:658
>  ShowTextCheckBoxOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:653
>  UpdateAutoShotTimer = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:212
>  BackplaneAlphaOnValChange = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:765
>  ClassicBarsCheckBoxOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:642
>  FeignFullReset = false
>  range_weapon_id = 186071
>  UpdateVisualsOnSettingsChange = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:445
>  is_spell_shoot = <function> defined @Interface\AddOns\WeaponSwingTimer\WeaponSwingTimer_Hunter.lua:49
>  ShowAutoShotDelayCheckBoxOnClick = <function> defined @Interface\AddOns\WeaponSwingTimer

**Comment by watchyoursixx** [comment]
should have a fix for this in v 6.3.4
