### ISSUE TITLE
"Jumping" Shottimer if LOS

### ISSUE THREAD

**Issue by Erlhojok** [watchyoursixx/WeaponSwingTimer-SixxFix#35]
I don't know if it is supposed to work like this. If you LOS your target while having Auto Shot toggled it makes the bar for the Auto Shot jump. It seems to jump between the middle of the whole bar and the beginning of the "don't cast Multishot" bar. I don't know how to describe it better.

**Comment by watchyoursixx** [comment]
There's a setting called "show auto shot delay" which is what this is. Every time auto shot tries to cast but can't, it starts a 0.5s timer before checking again. This is just displaying that timer because of you don't have it, it will just show you're ready to shoot and it's not going out.

**Comment by Erlhojok** [comment]
Ok, thanks a lot for clarifying that! Sorry for opening an issue that wasn't really an issue. Thank you for your improvements to the Swing Timer in general! It is way more accurate.
