### ISSUE TITLE
Bar progress reset during melee weaving.

### ISSUE THREAD

**Issue by LordBumi** [watchyoursixx/WeaponSwingTimer-SixxFix#38]
Bar often rapidly resets while moving , (even when autoshot delay timer is not selected ).
The issue becomes apparent when trying to weave. Most of the times the swing bar becomes unreadable  during quick movement like that .

**Comment by watchyoursixx** [comment]
Unsure how to fix this at the moment but I'm aware of it

**Comment by watchyoursixx** [comment]
this was fixed in v6.5.0
