### ISSUE TITLE
[Bug] TBC is not resetting swingtimer on slam highest rank properly

### ISSUE THREAD

**Issue by cordankos** [watchyoursixx/WeaponSwingTimer-SixxFix#39]
Fix is WeaponSwingTime_Core.lua adding 25242 id to line 518

**Comment by watchyoursixx** [comment]
I'll try to publish a fix for this and several others sometime this week. I've been really busy

**Comment by jordanwelzbacher** [comment]
Can fix locally with this in the meantime:

Change line 518 in WeaponSwingTimer_Core.lua

From:
--[[ Slam ]]                    1464, 8820, 11604, 11605, 25241,

To:
--[[ Slam ]]                    1464, 8820, 11604, 11605, 25241, 25242
