### ISSUE TITLE
The compability of this addon about 1.12 version  Turtle wow

### ISSUE THREAD

**Issue by ZonghuiWang** [watchyoursixx/WeaponSwingTimer-SixxFix#59]
Hello developer! Do you know Turtle WOW? A parallel world Vanilla verison based on 1.12 and I highle recommend you to play it!! I have been used WST on the offical server, if you can make this addon compatible with version 1.12 Turtle wow? Thank you !

**Comment by watchyoursixx** [comment]
Someone else is welcome to try converting, but I think the difference between vanilla wow and current game is too much to make this a simple conversion. Closing as unplanned.
