### ISSUE TITLE
[Cata Classic] Options panel errors after 4.4.1

### ISSUE THREAD

**Issue by Road-block** [watchyoursixx/WeaponSwingTimer-SixxFix#75]
Fix(es)
1. Replace instances of 
```lua
        InterfaceOptionsFrame_OpenToCategory("WeaponSwingTimer")
        InterfaceOptionsFrame_OpenToCategory("WeaponSwingTimer")
```
with
```lua
if _G.InterfaceOptionsFrame_OpenToCategory then
    InterfaceOptionsFrame_OpenToCategory("WeaponSwingTimer")
    InterfaceOptionsFrame_OpenToCategory("WeaponSwingTimer")
elseif Settings and Settings.OpenToCategory then
    Settings.OpenToCategory(addon_data.options_category.ID)
end
```
(one in the slash handler)

2. Replace instances of 
```lua
InterfaceOptions_AddCategory(<blah>)
```
with respectively (main category, melee, hunter)
```lua
if _G.InterfaceOptions_AddCategory then
    InterfaceOptions_AddCategory(panel)
elseif Settings and Settings.RegisterCanvasLayoutCategory then
    panel.OnDefault = panel.default
    local cat = Settings.RegisterCanvasLayoutCategory(panel, panel.name)
    cat.ID = panel.name
    Settings.RegisterAddOnCategory(cat)
    addon_data.options_category = cat
end
```
```lua
if _G.InterfaceOptions_AddCategory then
    InterfaceOptions_AddCategory(panel.config_melee_panel)
elseif Settings and Settings.RegisterCanvasLayoutSubcategory then
    panel.config_melee_panel.OnDefault = panel.default
    local subCat = Settings.RegisterCanvasLayoutSubcategory(addon_data.options_category, panel.config_melee_panel, panel.config_melee_panel.name)
end
```
```lua
    if _G.InterfaceOptions_AddCategory then
        InterfaceOptions_AddCategory(panel.config_hunter_panel)
    elseif Settings and Settings.RegisterCanvasLayoutSubcategory then
        panel.config_hunter_panel.OnDefault = panel.default
        local subCat = Settings.RegisterCanvasLayoutSubcategory(addon_data.options_category, panel.config_hunter_panel, panel.config_hunter_panel.name)
    end
```
(three places in _Config.lua)

**Comment by Road-block** [comment]
This would probably also fix similar errors in 1.15.4.

**Comment by rbpaiett** [comment]
Probably not since there's no 'interfaceoptions' anywhere in Options.lua.

**Comment by Road-block** [comment]
> Probably not since there's no 'interfaceoptions' anywhere in Options.lua.

I don't think you understand the code. 
The conditionals ensure that InterfaceOptions methods are **only** used if they exist on the client.
If they don't the modern Settings API is used.

**Comment by rbpaiett** [comment]
The very first line states to replace:

        InterfaceOptionsFrame_OpenToCategory("WeaponSwingTimer")
        InterfaceOptionsFrame_OpenToCategory("WeaponSwingTimer")

If those two lines don't exist in Classic Era's Config.lua, what will I be replacing instead?

UPDATE:

Oh I get it, nm, lol.

**Comment by Road-block** [comment]
For folks that are not comfortable doing source edits, here's a test package.
[WeaponSwingTimer-test-fix.zip](https://github.com/user-attachments/files/17693459/WeaponSwingTimer-test-fix.zip)

I know it works in Cata Classic, haven't tested Vanilla flavors but if the errors are options related it will likely work there as well.

**Comment by rbpaiett** [comment]
Actually, the latest version as it stands does work for Classic Era.

**Comment by hadrien-g** [comment]
wow I was looking for that, amazing THANKS so much !

**Comment by Road-block** [comment]
Last push seems to have a applied a similar fix.
